DROP TABLE IF EXISTS categories, requests, compilation_events, event_states, events, users, compilations, locations;

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT categories_pk PRIMARY KEY (id),
    CONSTRAINT categories_name_uq UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_email_uq UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lat FLOAT,
    lon FLOAT,
    CONSTRAINT locations_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state              VARCHAR(30)                             NOT NULL,
    title              VARCHAR(120)                            NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    description        VARCHAR(7000)                           NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    event_date         TIMESTAMP,
    created_on         TIMESTAMP,
    location_id        BIGINT,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  BIGINT  DEFAULT 0,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN DEFAULT TRUE,
    CONSTRAINT events_pk PRIMARY KEY (id),
    CONSTRAINT events_category_id_fk FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT events_users_id_fk FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT events_location_id_fk FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    status       VARCHAR(30)                             NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    created      TIMESTAMP,
    CONSTRAINT requests_pk PRIMARY KEY (id),
    CONSTRAINT requests_event_id_fk FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT requests_requester_id_fk FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
    unique (requester_id, event_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(120)                            NOT NULL,
    CONSTRAINT compilations_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comp_id  BIGINT,
    event_id BIGINT,
    CONSTRAINT compilation_events_PK PRIMARY KEY (id),
    CONSTRAINT compilation_events_comp_id_FK FOREIGN KEY (comp_id) REFERENCES compilations ON DELETE CASCADE,
    CONSTRAINT compilation_events_event_id_FK FOREIGN KEY (event_id) REFERENCES events
);



